import asyncio
import datetime
from collections import deque
from operator import ge, le, gt, lt
from typing import Any, Optional

from app.storage.values import Value


class StreamStorage:
    def __init__(self):
        self.data: dict[str, deque[Value]] = {}
        self.conditions: dict[Any, asyncio.Condition] = {}

    async def set_stream(self, key: str, value: Value) -> str:
        # TODO keep content not in dict, but in dataclass
        rec_id = value.item["id"]
        # When the format "*", "0-*" or "3-1" is violated we throw and exception
        if rec_id != "*" and len(rec_id.split("-")) != 2:
            raise ValueError("Invalid stream id")

        stream_id = await self._autogenerate_and_set_stream_id(key, value)
        if stream_id is None:
            stream_id = await self._set_stream_id(key, value)

        if key in self.conditions:
            async with self.conditions[key]:
                self.conditions[key].notify_all()

        return stream_id

    async def get_stream_range(
        self,
        key: str,
        start: tuple[int, int],
        end: tuple[int | float, int | float],
        is_inclusive: bool = True,
        blocking_period: Optional[int] = None,
    ) -> list[Value]:
        res = []
        if blocking_period == 0:
            if key not in self.conditions:
                self.conditions[key] = asyncio.Condition()

            def _data_available() -> bool:
                return (
                    key in self.data
                    and self._create_range(
                        self.data[key], start, end, is_inclusive=is_inclusive
                    )
                    != []
                )

            async with self.conditions[key]:
                await asyncio.wait_for(
                    self.conditions[key].wait_for(_data_available),
                    None,
                )
            res = self._create_range(
                self.data[key], start, end, is_inclusive=is_inclusive
            )
        elif blocking_period is not None:
            await asyncio.sleep(
                blocking_period / 1000
            )  # Converting milliseconds to seconds

        if key not in self.data:
            return res
        else:
            res = self._create_range(
                self.data[key], start, end, is_inclusive=is_inclusive
            )

        return res

    # TODO Consider the using a separate class for the streamID generation
    async def _autogenerate_and_set_stream_id(
        self, key: str, value: Value
    ) -> Optional[str]:
        rec_id = value.item["id"]
        if rec_id == "*":
            # This branch is for full id generation
            auto_timestmp = int(datetime.datetime.now(datetime.UTC).timestamp() * 1000)
            auto_version = 0
            value.item["id"] = f"{auto_timestmp}-{auto_version}"

            if key not in self.data:
                # new autogenerated record
                self.data[key] = deque([value])
            else:
                # some records already exist, define the id based on the last timestamp and the version
                last_timestmp, last_version = [
                    int(x) for x in self.data[key][-1].item["id"].split("-")
                ]
                if auto_timestmp == last_timestmp:
                    value.item["id"] = f"{auto_timestmp}-{last_version + 1}"
                else:
                    value.item["id"] = f"{auto_timestmp}-{auto_version}"
                self.data[key].append(value)
            return value.item["id"]
        else:
            # This branch is for partial id generation
            time_versioned = rec_id.split("-")
            if time_versioned[1] == "*" and key not in self.data:
                # The version is autogenerated for a new record
                value.item["id"] = f"{time_versioned[0]}-1"

                self.data[key] = deque([value])
                return value.item["id"]
            elif time_versioned[1] == "*" and key in self.data:
                # some records already exist, define the id based on the last timestamp and the version
                cur_timestmp = int(time_versioned[0])
                last_timestmp, last_version = [
                    int(x) for x in self.data[key][-1].item["id"].split("-")
                ]
                if cur_timestmp == last_timestmp:
                    # same timestamps in the ids
                    value.item["id"] = f"{time_versioned[0]}-{last_version + 1}"
                    self.data[key].append(value)
                    return value.item["id"]
                elif cur_timestmp < last_timestmp:
                    raise ValueError(
                        "The ID specified in XADD is equal or smaller than the target stream top item"
                    )
                else:
                    # different timestamps
                    value.item["id"] = f"{cur_timestmp}-0"
                    self.data[key].append(value)
                    return value.item["id"]
            return None

    async def _set_stream_id(self, key: str, value: Value) -> str:
        time_versioned = value.item["id"].split("-")
        timestmp, version = [int(x) for x in time_versioned]
        if timestmp < 0 or version < 1:
            raise ValueError("The ID specified in XADD must be greater than 0-0")

        if key not in self.data:
            self.data[key] = deque([value])
            return value.item["id"]

        last_timestmp, last_version = [
            int(x) for x in self.data[key][-1].item["id"].split("-")
        ]
        if timestmp < last_timestmp or (
            timestmp == last_timestmp and version <= last_version
        ):
            raise ValueError(
                "The ID specified in XADD is equal or smaller than the target stream top item"
            )
        self.data[key].append(value)
        return value.item["id"]

    def _create_range(
        self,
        stream: deque[Value],
        start: tuple[int, int],
        end: tuple[int | float, int | float],
        is_inclusive: bool,
    ) -> list[Value]:
        res = []
        if is_inclusive:
            lower_compare = ge
            upper_compare = le
        else:
            lower_compare = gt
            upper_compare = lt

        # TODO use binary search as this sequence is sorted by the timestamp
        for value in stream:
            timestamp, version = list(map(int, value.item["id"].split("-")))
            if (
                (end[0] > timestamp > start[0])
                or (
                    timestamp == start[0]
                    and timestamp == end[0]
                    and lower_compare(end[1], version)
                    and lower_compare(version, start[1])
                )
                or (
                    timestamp == start[0]
                    and timestamp != end[0]
                    and lower_compare(version, start[1])
                )
                or (
                    timestamp != start[0]
                    and timestamp == end[0]
                    and upper_compare(version, end[1])
                )
            ):
                res.append(value)

        return res
